[package]
name = "solana_hello_world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.108", features = [] }
